// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"anjuke/server/internal/biz"
	"anjuke/server/internal/conf"
	"anjuke/server/internal/data"
	"anjuke/server/internal/server"
	"anjuke/server/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.MysqlInit(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.ExampleClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	minioClient, err := data.NewMinioClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, logger, db, client, minioClient)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	realNameSDK := data.NewRealNameSDK(confData)
	userRepo := data.NewUserRepo(dataData, realNameSDK, logger)
	string2 := data.ProvideShumaiAppCode(confData)
	shumaiSmsSender := data.NewShumaiSmsSenderWithDeps(string2, client)
	smsRepo := data.NewSmsRepo(shumaiSmsSender)
	userUsecase := biz.NewUserUsecase(userRepo, smsRepo, minioClient, logger)
	userService := service.NewUserService(userUsecase)
	houseRepo := data.NewHouseRepo(dataData, logger)
	houseUsecase := biz.NewHouseUsecase(houseRepo, logger)
	houseService := service.NewHouseService(houseUsecase)
	transactionRepo := data.NewTransactionRepo(dataData, logger)
	transactionUsecase := biz.NewTransactionUsecase(transactionRepo, logger)
	transactionService := service.NewTransactionService(transactionUsecase)
	pointsRepo := data.NewPointsRepo(dataData, logger)
	pointsUsecase := biz.NewPointsUsecase(pointsRepo, logger)
	pointsService := service.NewPointsService(pointsUsecase)
	customerRepo := data.NewCustomerRepo(dataData, logger)
	customerUsecase := biz.NewCustomerUsecase(customerRepo, logger)
	customerService := service.NewCustomerService(customerUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, userService, houseService, transactionService, pointsService, customerService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, userService, houseService, transactionService, pointsService, customerService, minioClient, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
