// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: customer/v6/customer.proto

package v6

import (
	v1 "anjuke/server/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_customer_v6_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v6_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_v6_customer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// 创建客户响应数据
type CreateCustomerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerData) Reset() {
	*x = CreateCustomerData{}
	mi := &file_customer_v6_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerData) ProtoMessage() {}

func (x *CreateCustomerData) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v6_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerData.ProtoReflect.Descriptor instead.
func (*CreateCustomerData) Descriptor() ([]byte, []int) {
	return file_customer_v6_customer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerData) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateCustomerData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCustomerData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCustomerData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateCustomerData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_customer_v6_customer_proto protoreflect.FileDescriptor

const file_customer_v6_customer_proto_rawDesc = "" +
	"\n" +
	"\x1acustomer/v6/customer.proto\x12\x0fapi.customer.v6\x1a\x1cgoogle/api/annotations.proto\x1a\x16common/v1/common.proto\"q\n" +
	"\x15CreateCustomerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"\xae\x01\n" +
	"\x12CreateCustomerData\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt2~\n" +
	"\bCustomer\x12r\n" +
	"\x0eCreateCustomer\x12&.api.customer.v6.CreateCustomerRequest\x1a\x1b.api.common.v1.BaseResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/customer/createBF\n" +
	"\x0fapi.customer.v6B\x0fCustomerProtoV6P\x01Z anjuke/server/api/customer/v6;v6b\x06proto3"

var (
	file_customer_v6_customer_proto_rawDescOnce sync.Once
	file_customer_v6_customer_proto_rawDescData []byte
)

func file_customer_v6_customer_proto_rawDescGZIP() []byte {
	file_customer_v6_customer_proto_rawDescOnce.Do(func() {
		file_customer_v6_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_v6_customer_proto_rawDesc), len(file_customer_v6_customer_proto_rawDesc)))
	})
	return file_customer_v6_customer_proto_rawDescData
}

var file_customer_v6_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_customer_v6_customer_proto_goTypes = []any{
	(*CreateCustomerRequest)(nil), // 0: api.customer.v6.CreateCustomerRequest
	(*CreateCustomerData)(nil),    // 1: api.customer.v6.CreateCustomerData
	(*v1.BaseResponse)(nil),       // 2: api.common.v1.BaseResponse
}
var file_customer_v6_customer_proto_depIdxs = []int32{
	0, // 0: api.customer.v6.Customer.CreateCustomer:input_type -> api.customer.v6.CreateCustomerRequest
	2, // 1: api.customer.v6.Customer.CreateCustomer:output_type -> api.common.v1.BaseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_customer_v6_customer_proto_init() }
func file_customer_v6_customer_proto_init() {
	if File_customer_v6_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_v6_customer_proto_rawDesc), len(file_customer_v6_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_v6_customer_proto_goTypes,
		DependencyIndexes: file_customer_v6_customer_proto_depIdxs,
		MessageInfos:      file_customer_v6_customer_proto_msgTypes,
	}.Build()
	File_customer_v6_customer_proto = out.File
	file_customer_v6_customer_proto_goTypes = nil
	file_customer_v6_customer_proto_depIdxs = nil
}
