// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/user/v2/user.proto

package v2

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateUserRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

// todo 登录/注册
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 用户名
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`             // 手机号
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`       // 密码
	SendSmsCode   string                 `protobuf:"bytes,4,opt,name=sendSmsCode,proto3" json:"sendSmsCode,omitempty"` // 验证码
	Sex           string                 `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`                 // 性别
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

func (x *LoginRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // JWT token
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`               // 用户状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// todo 短信验证码
type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{4}
}

func (x *SendSmsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendSmsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SendSmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReply) Reset() {
	*x = SendSmsReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReply) ProtoMessage() {}

func (x *SendSmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReply.ProtoReflect.Descriptor instead.
func (*SendSmsReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{5}
}

func (x *SendSmsReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

// todo 用户个人信息修改
type UpdateUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                       // 用户id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                    // 新昵称
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`                  // 手机号
	Sex           string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`                      // 性别
	RoleId        int64                  `protobuf:"varint,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 角色id
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                // 头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UpdateUserInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateUserInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // 修改是否成功
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 消息提示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoReply) Reset() {
	*x = UpdateUserInfoReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoReply) ProtoMessage() {}

func (x *UpdateUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoReply.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserInfoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserInfoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// todo 用户密码修改
type UpdateUserPwsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                 // 用户id
	Phone           string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`                                            // 手机号
	OldPassword     string                 `protobuf:"bytes,4,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`             // 旧密码
	Password        string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`                                      // 新密码
	ConfirmPassword string                 `protobuf:"bytes,6,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"` // 确认密码
	SendSmsCode     string                 `protobuf:"bytes,7,opt,name=send_sms_code,json=sendSmsCode,proto3" json:"send_sms_code,omitempty"`           // 验证码
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserPwsRequest) Reset() {
	*x = UpdateUserPwsRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPwsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPwsRequest) ProtoMessage() {}

func (x *UpdateUserPwsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPwsRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPwsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserPwsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserPwsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserPwsRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdateUserPwsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserPwsRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *UpdateUserPwsRequest) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

type UpdateUserPwsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 消息提示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPwsReply) Reset() {
	*x = UpdateUserPwsReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPwsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPwsReply) ProtoMessage() {}

func (x *UpdateUserPwsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPwsReply.ProtoReflect.Descriptor instead.
func (*UpdateUserPwsReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserPwsReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// todo 支付宝人脸识别实名认证
type FaceCertifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                    // 用户ID
	RealName      string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`               // 真实姓名
	IdCardNumber  string                 `protobuf:"bytes,3,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"` // 身份证号
	ReturnUrl     string                 `protobuf:"bytes,4,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`            // 认证完成后的回调地址（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceCertifyRequest) Reset() {
	*x = FaceCertifyRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceCertifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceCertifyRequest) ProtoMessage() {}

func (x *FaceCertifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceCertifyRequest.ProtoReflect.Descriptor instead.
func (*FaceCertifyRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{10}
}

func (x *FaceCertifyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FaceCertifyRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *FaceCertifyRequest) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *FaceCertifyRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

type FaceCertifyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertifyId     string                 `protobuf:"bytes,1,opt,name=certify_id,json=certifyId,proto3" json:"certify_id,omitempty"`    // 认证ID
	CertifyUrl    string                 `protobuf:"bytes,2,opt,name=certify_url,json=certifyUrl,proto3" json:"certify_url,omitempty"` // 认证URL，用户需要访问此URL完成人脸识别
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                        // 是否成功
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceCertifyReply) Reset() {
	*x = FaceCertifyReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceCertifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceCertifyReply) ProtoMessage() {}

func (x *FaceCertifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceCertifyReply.ProtoReflect.Descriptor instead.
func (*FaceCertifyReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{11}
}

func (x *FaceCertifyReply) GetCertifyId() string {
	if x != nil {
		return x.CertifyId
	}
	return ""
}

func (x *FaceCertifyReply) GetCertifyUrl() string {
	if x != nil {
		return x.CertifyUrl
	}
	return ""
}

func (x *FaceCertifyReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FaceCertifyReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// todo 支付宝实名认证回调
type CertifyNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyType    string                 `protobuf:"bytes,1,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"` // 通知类型
	NotifyId      string                 `protobuf:"bytes,2,opt,name=notify_id,json=notifyId,proto3" json:"notify_id,omitempty"`       // 通知ID
	SignType      string                 `protobuf:"bytes,3,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`       // 签名类型
	Sign          string                 `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`                               // 签名
	Charset       string                 `protobuf:"bytes,5,opt,name=charset,proto3" json:"charset,omitempty"`                         // 字符集
	BizContent    string                 `protobuf:"bytes,6,opt,name=biz_content,json=bizContent,proto3" json:"biz_content,omitempty"` // 业务内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertifyNotifyRequest) Reset() {
	*x = CertifyNotifyRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertifyNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertifyNotifyRequest) ProtoMessage() {}

func (x *CertifyNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertifyNotifyRequest.ProtoReflect.Descriptor instead.
func (*CertifyNotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{12}
}

func (x *CertifyNotifyRequest) GetNotifyType() string {
	if x != nil {
		return x.NotifyType
	}
	return ""
}

func (x *CertifyNotifyRequest) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

func (x *CertifyNotifyRequest) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *CertifyNotifyRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *CertifyNotifyRequest) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *CertifyNotifyRequest) GetBizContent() string {
	if x != nil {
		return x.BizContent
	}
	return ""
}

type CertifyNotifyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // 处理结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertifyNotifyReply) Reset() {
	*x = CertifyNotifyReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertifyNotifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertifyNotifyReply) ProtoMessage() {}

func (x *CertifyNotifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertifyNotifyReply.ProtoReflect.Descriptor instead.
func (*CertifyNotifyReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{13}
}

func (x *CertifyNotifyReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// todo 查询实名认证结果
type QueryCertifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertifyId     string                 `protobuf:"bytes,1,opt,name=certify_id,json=certifyId,proto3" json:"certify_id,omitempty"` // 认证ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCertifyRequest) Reset() {
	*x = QueryCertifyRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCertifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCertifyRequest) ProtoMessage() {}

func (x *QueryCertifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCertifyRequest.ProtoReflect.Descriptor instead.
func (*QueryCertifyRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{14}
}

func (x *QueryCertifyRequest) GetCertifyId() string {
	if x != nil {
		return x.CertifyId
	}
	return ""
}

func (x *QueryCertifyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type QueryCertifyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`                                  // 认证是否通过
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                   // 认证状态：INITIAL(初始化), PROCESSING(处理中), SUCCESS(成功), FAIL(失败)
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`               // 真实姓名
	IdCardNumber  string                 `protobuf:"bytes,4,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"` // 身份证号
	FailReason    string                 `protobuf:"bytes,5,opt,name=fail_reason,json=failReason,proto3" json:"fail_reason,omitempty"`         // 失败原因（如果认证失败）
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                 // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCertifyReply) Reset() {
	*x = QueryCertifyReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCertifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCertifyReply) ProtoMessage() {}

func (x *QueryCertifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCertifyReply.ProtoReflect.Descriptor instead.
func (*QueryCertifyReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{15}
}

func (x *QueryCertifyReply) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *QueryCertifyReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryCertifyReply) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *QueryCertifyReply) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *QueryCertifyReply) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

func (x *QueryCertifyReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// todo 密码重置
type ResetPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Phone           string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`                                            // 手机号
	SmsCode         string                 `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`                         // 短信验证码
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`             // 新密码
	ConfirmPassword string                 `protobuf:"bytes,4,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"` // 确认密码
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{16}
}

func (x *ResetPasswordRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResetPasswordRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetPasswordRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type ResetPasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReply) Reset() {
	*x = ResetPasswordReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReply) ProtoMessage() {}

func (x *ResetPasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReply.ProtoReflect.Descriptor instead.
func (*ResetPasswordReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{17}
}

func (x *ResetPasswordReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetPasswordReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// todo 账号冻结
type FreezeAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                   // 冻结原因
	AdminId       int64                  `protobuf:"varint,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"` // 操作管理员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeAccountRequest) Reset() {
	*x = FreezeAccountRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeAccountRequest) ProtoMessage() {}

func (x *FreezeAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeAccountRequest.ProtoReflect.Descriptor instead.
func (*FreezeAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{18}
}

func (x *FreezeAccountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FreezeAccountRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FreezeAccountRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type FreezeAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeAccountReply) Reset() {
	*x = FreezeAccountReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeAccountReply) ProtoMessage() {}

func (x *FreezeAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeAccountReply.ProtoReflect.Descriptor instead.
func (*FreezeAccountReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{19}
}

func (x *FreezeAccountReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FreezeAccountReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// todo 账号解冻
type UnfreezeAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                   // 解冻原因
	AdminId       int64                  `protobuf:"varint,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"` // 操作管理员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfreezeAccountRequest) Reset() {
	*x = UnfreezeAccountRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreezeAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreezeAccountRequest) ProtoMessage() {}

func (x *UnfreezeAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreezeAccountRequest.ProtoReflect.Descriptor instead.
func (*UnfreezeAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{20}
}

func (x *UnfreezeAccountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfreezeAccountRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UnfreezeAccountRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type UnfreezeAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfreezeAccountReply) Reset() {
	*x = UnfreezeAccountReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreezeAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreezeAccountReply) ProtoMessage() {}

func (x *UnfreezeAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreezeAccountReply.ProtoReflect.Descriptor instead.
func (*UnfreezeAccountReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{21}
}

func (x *UnfreezeAccountReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnfreezeAccountReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// todo 获取登录日志
type GetLoginLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginLogsRequest) Reset() {
	*x = GetLoginLogsRequest{}
	mi := &file_api_user_v2_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginLogsRequest) ProtoMessage() {}

func (x *GetLoginLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLoginLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetLoginLogsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLoginLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLoginLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetLoginLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LoginLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`                          // 登录日志列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数量
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginLogsReply) Reset() {
	*x = GetLoginLogsReply{}
	mi := &file_api_user_v2_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginLogsReply) ProtoMessage() {}

func (x *GetLoginLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginLogsReply.ProtoReflect.Descriptor instead.
func (*GetLoginLogsReply) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{23}
}

func (x *GetLoginLogsReply) GetLogs() []*LoginLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetLoginLogsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetLoginLogsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLoginLogsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 登录日志信息
type LoginLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 日志ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户ID
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`        // IP地址
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`        // 用户代理
	DeviceInfo    string                 `protobuf:"bytes,5,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`     // 设备信息
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`                           // 登录地点
	LoginStatus   int32                  `protobuf:"varint,7,opt,name=login_status,json=loginStatus,proto3" json:"login_status,omitempty"` // 登录状态 (1:成功 0:失败)
	FailReason    string                 `protobuf:"bytes,8,opt,name=fail_reason,json=failReason,proto3" json:"fail_reason,omitempty"`     // 失败原因
	LoginTime     int64                  `protobuf:"varint,9,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`       // 登录时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLog) Reset() {
	*x = LoginLog{}
	mi := &file_api_user_v2_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLog) ProtoMessage() {}

func (x *LoginLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v2_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLog.ProtoReflect.Descriptor instead.
func (*LoginLog) Descriptor() ([]byte, []int) {
	return file_api_user_v2_user_proto_rawDescGZIP(), []int{24}
}

func (x *LoginLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginLog) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginLog) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoginLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LoginLog) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

func (x *LoginLog) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *LoginLog) GetLoginStatus() int32 {
	if x != nil {
		return x.LoginStatus
	}
	return 0
}

func (x *LoginLog) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

func (x *LoginLog) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

var File_api_user_v2_user_proto protoreflect.FileDescriptor

const file_api_user_v2_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v2/user.proto\x12\vapi.user.v2\x1a\x1cgoogle/api/annotations.proto\"c\n" +
	"\x11CreateUserRequest\x12\x16\n" +
	"\x06Mobile\x18\x01 \x01(\tR\x06Mobile\x12\x1a\n" +
	"\bNickName\x18\x02 \x01(\tR\bNickName\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"+\n" +
	"\x0fCreateUserReply\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\tR\aSuccess\"\x88\x01\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12 \n" +
	"\vsendSmsCode\x18\x04 \x01(\tR\vsendSmsCode\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\tR\x03sex\"S\n" +
	"\n" +
	"LoginReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\">\n" +
	"\x0eSendSmsRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"(\n" +
	"\fSendSmsReply\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\tR\aSuccess\"\x94\x01\n" +
	"\x15UpdateUserInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\x03R\x06roleId\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\"?\n" +
	"\x13UpdateUserInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xca\x01\n" +
	"\x14UpdateUserPwsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12!\n" +
	"\fold_password\x18\x04 \x01(\tR\voldPassword\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x06 \x01(\tR\x0fconfirmPassword\x12\"\n" +
	"\rsend_sms_code\x18\a \x01(\tR\vsendSmsCode\".\n" +
	"\x12UpdateUserPwsReply\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x8f\x01\n" +
	"\x12FaceCertifyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12$\n" +
	"\x0eid_card_number\x18\x03 \x01(\tR\fidCardNumber\x12\x1d\n" +
	"\n" +
	"return_url\x18\x04 \x01(\tR\treturnUrl\"\x86\x01\n" +
	"\x10FaceCertifyReply\x12\x1d\n" +
	"\n" +
	"certify_id\x18\x01 \x01(\tR\tcertifyId\x12\x1f\n" +
	"\vcertify_url\x18\x02 \x01(\tR\n" +
	"certifyUrl\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xc0\x01\n" +
	"\x14CertifyNotifyRequest\x12\x1f\n" +
	"\vnotify_type\x18\x01 \x01(\tR\n" +
	"notifyType\x12\x1b\n" +
	"\tnotify_id\x18\x02 \x01(\tR\bnotifyId\x12\x1b\n" +
	"\tsign_type\x18\x03 \x01(\tR\bsignType\x12\x12\n" +
	"\x04sign\x18\x04 \x01(\tR\x04sign\x12\x18\n" +
	"\acharset\x18\x05 \x01(\tR\acharset\x12\x1f\n" +
	"\vbiz_content\x18\x06 \x01(\tR\n" +
	"bizContent\",\n" +
	"\x12CertifyNotifyReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"M\n" +
	"\x13QueryCertifyRequest\x12\x1d\n" +
	"\n" +
	"certify_id\x18\x01 \x01(\tR\tcertifyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xc1\x01\n" +
	"\x11QueryCertifyReply\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12$\n" +
	"\x0eid_card_number\x18\x04 \x01(\tR\fidCardNumber\x12\x1f\n" +
	"\vfail_reason\x18\x05 \x01(\tR\n" +
	"failReason\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x95\x01\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x19\n" +
	"\bsms_code\x18\x02 \x01(\tR\asmsCode\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\x12)\n" +
	"\x10confirm_password\x18\x04 \x01(\tR\x0fconfirmPassword\"H\n" +
	"\x12ResetPasswordReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x14FreezeAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\x03R\aadminId\"H\n" +
	"\x12FreezeAccountReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x16UnfreezeAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\x03R\aadminId\"J\n" +
	"\x14UnfreezeAccountReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x13GetLoginLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x85\x01\n" +
	"\x11GetLoginLogsReply\x12)\n" +
	"\x04logs\x18\x01 \x03(\v2\x15.api.user.v2.LoginLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x91\x02\n" +
	"\bLoginLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vdevice_info\x18\x05 \x01(\tR\n" +
	"deviceInfo\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12!\n" +
	"\flogin_status\x18\a \x01(\x05R\vloginStatus\x12\x1f\n" +
	"\vfail_reason\x18\b \x01(\tR\n" +
	"failReason\x12\x1d\n" +
	"\n" +
	"login_time\x18\t \x01(\x03R\tloginTime2\xb0\n" +
	"\n" +
	"\x04User\x12c\n" +
	"\n" +
	"CreateUser\x12\x1e.api.user.v2.CreateUserRequest\x1a\x1c.api.user.v2.CreateUserReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/user/create\x12S\n" +
	"\x05Login\x12\x19.api.user.v2.LoginRequest\x1a\x17.api.user.v2.LoginReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/login\x12W\n" +
	"\aSendSms\x12\x1b.api.user.v2.SendSmsRequest\x1a\x19.api.user.v2.SendSmsReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/user/sms\x12t\n" +
	"\x0eUpdateUserInfo\x12\".api.user.v2.UpdateUserInfoRequest\x1a .api.user.v2.UpdateUserInfoReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/user/update_info\x12p\n" +
	"\rUpdateUserPws\x12!.api.user.v2.UpdateUserPwsRequest\x1a\x1f.api.user.v2.UpdateUserPwsReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/user/update_pws\x12l\n" +
	"\vFaceCertify\x12\x1f.api.user.v2.FaceCertifyRequest\x1a\x1d.api.user.v2.FaceCertifyReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/user/face_certify\x12t\n" +
	"\rCertifyNotify\x12!.api.user.v2.CertifyNotifyRequest\x1a\x1f.api.user.v2.CertifyNotifyReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/user/certify_notify\x12p\n" +
	"\fQueryCertify\x12 .api.user.v2.QueryCertifyRequest\x1a\x1e.api.user.v2.QueryCertifyReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/user/query_certify\x12t\n" +
	"\rResetPassword\x12!.api.user.v2.ResetPasswordRequest\x1a\x1f.api.user.v2.ResetPasswordReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/user/reset_password\x12t\n" +
	"\rFreezeAccount\x12!.api.user.v2.FreezeAccountRequest\x1a\x1f.api.user.v2.FreezeAccountReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/user/freeze_account\x12|\n" +
	"\x0fUnfreezeAccount\x12#.api.user.v2.UnfreezeAccountRequest\x1a!.api.user.v2.UnfreezeAccountReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/user/unfreeze_account\x12m\n" +
	"\fGetLoginLogs\x12 .api.user.v2.GetLoginLogsRequest\x1a\x1e.api.user.v2.GetLoginLogsReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/user/login_logsB3\n" +
	"\vapi.user.v2B\vUserProtoV2P\x01Z\x15anjuke/api/user/v2;v2b\x06proto3"

var (
	file_api_user_v2_user_proto_rawDescOnce sync.Once
	file_api_user_v2_user_proto_rawDescData []byte
)

func file_api_user_v2_user_proto_rawDescGZIP() []byte {
	file_api_user_v2_user_proto_rawDescOnce.Do(func() {
		file_api_user_v2_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v2_user_proto_rawDesc), len(file_api_user_v2_user_proto_rawDesc)))
	})
	return file_api_user_v2_user_proto_rawDescData
}

var file_api_user_v2_user_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_user_v2_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),      // 0: api.user.v2.CreateUserRequest
	(*CreateUserReply)(nil),        // 1: api.user.v2.CreateUserReply
	(*LoginRequest)(nil),           // 2: api.user.v2.LoginRequest
	(*LoginReply)(nil),             // 3: api.user.v2.LoginReply
	(*SendSmsRequest)(nil),         // 4: api.user.v2.SendSmsRequest
	(*SendSmsReply)(nil),           // 5: api.user.v2.SendSmsReply
	(*UpdateUserInfoRequest)(nil),  // 6: api.user.v2.UpdateUserInfoRequest
	(*UpdateUserInfoReply)(nil),    // 7: api.user.v2.UpdateUserInfoReply
	(*UpdateUserPwsRequest)(nil),   // 8: api.user.v2.UpdateUserPwsRequest
	(*UpdateUserPwsReply)(nil),     // 9: api.user.v2.UpdateUserPwsReply
	(*FaceCertifyRequest)(nil),     // 10: api.user.v2.FaceCertifyRequest
	(*FaceCertifyReply)(nil),       // 11: api.user.v2.FaceCertifyReply
	(*CertifyNotifyRequest)(nil),   // 12: api.user.v2.CertifyNotifyRequest
	(*CertifyNotifyReply)(nil),     // 13: api.user.v2.CertifyNotifyReply
	(*QueryCertifyRequest)(nil),    // 14: api.user.v2.QueryCertifyRequest
	(*QueryCertifyReply)(nil),      // 15: api.user.v2.QueryCertifyReply
	(*ResetPasswordRequest)(nil),   // 16: api.user.v2.ResetPasswordRequest
	(*ResetPasswordReply)(nil),     // 17: api.user.v2.ResetPasswordReply
	(*FreezeAccountRequest)(nil),   // 18: api.user.v2.FreezeAccountRequest
	(*FreezeAccountReply)(nil),     // 19: api.user.v2.FreezeAccountReply
	(*UnfreezeAccountRequest)(nil), // 20: api.user.v2.UnfreezeAccountRequest
	(*UnfreezeAccountReply)(nil),   // 21: api.user.v2.UnfreezeAccountReply
	(*GetLoginLogsRequest)(nil),    // 22: api.user.v2.GetLoginLogsRequest
	(*GetLoginLogsReply)(nil),      // 23: api.user.v2.GetLoginLogsReply
	(*LoginLog)(nil),               // 24: api.user.v2.LoginLog
}
var file_api_user_v2_user_proto_depIdxs = []int32{
	24, // 0: api.user.v2.GetLoginLogsReply.logs:type_name -> api.user.v2.LoginLog
	0,  // 1: api.user.v2.User.CreateUser:input_type -> api.user.v2.CreateUserRequest
	2,  // 2: api.user.v2.User.Login:input_type -> api.user.v2.LoginRequest
	4,  // 3: api.user.v2.User.SendSms:input_type -> api.user.v2.SendSmsRequest
	6,  // 4: api.user.v2.User.UpdateUserInfo:input_type -> api.user.v2.UpdateUserInfoRequest
	8,  // 5: api.user.v2.User.UpdateUserPws:input_type -> api.user.v2.UpdateUserPwsRequest
	10, // 6: api.user.v2.User.FaceCertify:input_type -> api.user.v2.FaceCertifyRequest
	12, // 7: api.user.v2.User.CertifyNotify:input_type -> api.user.v2.CertifyNotifyRequest
	14, // 8: api.user.v2.User.QueryCertify:input_type -> api.user.v2.QueryCertifyRequest
	16, // 9: api.user.v2.User.ResetPassword:input_type -> api.user.v2.ResetPasswordRequest
	18, // 10: api.user.v2.User.FreezeAccount:input_type -> api.user.v2.FreezeAccountRequest
	20, // 11: api.user.v2.User.UnfreezeAccount:input_type -> api.user.v2.UnfreezeAccountRequest
	22, // 12: api.user.v2.User.GetLoginLogs:input_type -> api.user.v2.GetLoginLogsRequest
	1,  // 13: api.user.v2.User.CreateUser:output_type -> api.user.v2.CreateUserReply
	3,  // 14: api.user.v2.User.Login:output_type -> api.user.v2.LoginReply
	5,  // 15: api.user.v2.User.SendSms:output_type -> api.user.v2.SendSmsReply
	7,  // 16: api.user.v2.User.UpdateUserInfo:output_type -> api.user.v2.UpdateUserInfoReply
	9,  // 17: api.user.v2.User.UpdateUserPws:output_type -> api.user.v2.UpdateUserPwsReply
	11, // 18: api.user.v2.User.FaceCertify:output_type -> api.user.v2.FaceCertifyReply
	13, // 19: api.user.v2.User.CertifyNotify:output_type -> api.user.v2.CertifyNotifyReply
	15, // 20: api.user.v2.User.QueryCertify:output_type -> api.user.v2.QueryCertifyReply
	17, // 21: api.user.v2.User.ResetPassword:output_type -> api.user.v2.ResetPasswordReply
	19, // 22: api.user.v2.User.FreezeAccount:output_type -> api.user.v2.FreezeAccountReply
	21, // 23: api.user.v2.User.UnfreezeAccount:output_type -> api.user.v2.UnfreezeAccountReply
	23, // 24: api.user.v2.User.GetLoginLogs:output_type -> api.user.v2.GetLoginLogsReply
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_user_v2_user_proto_init() }
func file_api_user_v2_user_proto_init() {
	if File_api_user_v2_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v2_user_proto_rawDesc), len(file_api_user_v2_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v2_user_proto_goTypes,
		DependencyIndexes: file_api_user_v2_user_proto_depIdxs,
		MessageInfos:      file_api_user_v2_user_proto_msgTypes,
	}.Build()
	File_api_user_v2_user_proto = out.File
	file_api_user_v2_user_proto_goTypes = nil
	file_api_user_v2_user_proto_depIdxs = nil
}
