// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: api/order/v1/order.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTenantOrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` //租客ID
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantOrderListRequest) Reset() {
	*x = GetTenantOrderListRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantOrderListRequest) ProtoMessage() {}

func (x *GetTenantOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantOrderListRequest.ProtoReflect.Descriptor instead.
func (*GetTenantOrderListRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetTenantOrderListRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetTenantOrderListRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTenantOrderListRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTenantOrderListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantOrderListReply) Reset() {
	*x = GetTenantOrderListReply{}
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantOrderListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantOrderListReply) ProtoMessage() {}

func (x *GetTenantOrderListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantOrderListReply.ProtoReflect.Descriptor instead.
func (*GetTenantOrderListReply) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantOrderListReply) GetList() []*OrderInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetTenantOrderListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTenantOrderListReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTenantOrderListReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	HouseId       uint32                 `protobuf:"varint,3,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	TenantId      uint32                 `protobuf:"varint,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LandlordId    uint32                 `protobuf:"varint,5,opt,name=landlord_id,json=landlordId,proto3" json:"landlord_id,omitempty"`
	TenantPhone   string                 `protobuf:"bytes,6,opt,name=tenant_phone,json=tenantPhone,proto3" json:"tenant_phone,omitempty"`
	RentStart     string                 `protobuf:"bytes,7,opt,name=rent_start,json=rentStart,proto3" json:"rent_start,omitempty"`
	RentEnd       string                 `protobuf:"bytes,8,opt,name=rent_end,json=rentEnd,proto3" json:"rent_end,omitempty"`
	RentAmount    float64                `protobuf:"fixed64,9,opt,name=rent_amount,json=rentAmount,proto3" json:"rent_amount,omitempty"`
	Deposit       float64                `protobuf:"fixed64,10,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	SignedAt      string                 `protobuf:"bytes,12,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CancelReason  string                 `protobuf:"bytes,16,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"` // 取消原因
	CancelledAt   string                 `protobuf:"bytes,17,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`    // 取消时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderInfo) GetHouseId() uint32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *OrderInfo) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *OrderInfo) GetLandlordId() uint32 {
	if x != nil {
		return x.LandlordId
	}
	return 0
}

func (x *OrderInfo) GetTenantPhone() string {
	if x != nil {
		return x.TenantPhone
	}
	return ""
}

func (x *OrderInfo) GetRentStart() string {
	if x != nil {
		return x.RentStart
	}
	return ""
}

func (x *OrderInfo) GetRentEnd() string {
	if x != nil {
		return x.RentEnd
	}
	return ""
}

func (x *OrderInfo) GetRentAmount() float64 {
	if x != nil {
		return x.RentAmount
	}
	return 0
}

func (x *OrderInfo) GetDeposit() float64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *OrderInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfo) GetSignedAt() string {
	if x != nil {
		return x.SignedAt
	}
	return ""
}

func (x *OrderInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderInfo) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *OrderInfo) GetCancelledAt() string {
	if x != nil {
		return x.CancelledAt
	}
	return ""
}

type GetOrderDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailRequest) Reset() {
	*x = GetOrderDetailRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailRequest) ProtoMessage() {}

func (x *GetOrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderDetailRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailReply) Reset() {
	*x = GetOrderDetailReply{}
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailReply) ProtoMessage() {}

func (x *GetOrderDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailReply.ProtoReflect.Descriptor instead.
func (*GetOrderDetailReply) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderDetailReply) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListRequest) Reset() {
	*x = GetOrderListRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListRequest) ProtoMessage() {}

func (x *GetOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListRequest.ProtoReflect.Descriptor instead.
func (*GetOrderListRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderListRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderListRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetOrderListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListReply) Reset() {
	*x = GetOrderListReply{}
	mi := &file_api_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListReply) ProtoMessage() {}

func (x *GetOrderListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListReply.ProtoReflect.Descriptor instead.
func (*GetOrderListReply) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderListReply) GetList() []*OrderInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetOrderListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetOrderListReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderListReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseId       uint32                 `protobuf:"varint,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`            // 房源ID
	TenantId      uint32                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`         // 租客ID
	LandlordId    uint32                 `protobuf:"varint,3,opt,name=landlord_id,json=landlordId,proto3" json:"landlord_id,omitempty"`   // 房东ID
	TenantPhone   string                 `protobuf:"bytes,4,opt,name=tenant_phone,json=tenantPhone,proto3" json:"tenant_phone,omitempty"` // 租客手机号
	RentStart     string                 `protobuf:"bytes,5,opt,name=rent_start,json=rentStart,proto3" json:"rent_start,omitempty"`       // 租期开始时间 (YYYY-MM-DD)
	RentEnd       string                 `protobuf:"bytes,6,opt,name=rent_end,json=rentEnd,proto3" json:"rent_end,omitempty"`             // 租期结束时间 (YYYY-MM-DD)
	RentAmount    float64                `protobuf:"fixed64,7,opt,name=rent_amount,json=rentAmount,proto3" json:"rent_amount,omitempty"`  // 租金
	Deposit       float64                `protobuf:"fixed64,8,opt,name=deposit,proto3" json:"deposit,omitempty"`                          // 押金
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrderRequest) GetHouseId() uint32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *CreateOrderRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreateOrderRequest) GetLandlordId() uint32 {
	if x != nil {
		return x.LandlordId
	}
	return 0
}

func (x *CreateOrderRequest) GetTenantPhone() string {
	if x != nil {
		return x.TenantPhone
	}
	return ""
}

func (x *CreateOrderRequest) GetRentStart() string {
	if x != nil {
		return x.RentStart
	}
	return ""
}

func (x *CreateOrderRequest) GetRentEnd() string {
	if x != nil {
		return x.RentEnd
	}
	return ""
}

func (x *CreateOrderRequest) GetRentAmount() float64 {
	if x != nil {
		return x.RentAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetDeposit() float64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                // 返回消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_api_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrderReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 订单ID
	CancelReason  string                 `protobuf:"bytes,2,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"` // 取消原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CancelOrderRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type CancelOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`  // 返回消息
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReply) Reset() {
	*x = CancelOrderReply{}
	mi := &file_api_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReply) ProtoMessage() {}

func (x *CancelOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReply.ProtoReflect.Descriptor instead.
func (*CancelOrderReply) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelOrderReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_order_v1_order_proto protoreflect.FileDescriptor

const file_api_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x18api/order/v1/order.proto\x12\fapi.order.v1\x1a\x1cgoogle/api/annotations.proto\"i\n" +
	"\x19GetTenantOrderListRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x8d\x01\n" +
	"\x17GetTenantOrderListReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.api.order.v1.OrderInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb3\x03\n" +
	"\tOrderInfo\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x19\n" +
	"\bhouse_id\x18\x03 \x01(\rR\ahouseId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\rR\btenantId\x12\x1f\n" +
	"\vlandlord_id\x18\x05 \x01(\rR\n" +
	"landlordId\x12!\n" +
	"\ftenant_phone\x18\x06 \x01(\tR\vtenantPhone\x12\x1d\n" +
	"\n" +
	"rent_start\x18\a \x01(\tR\trentStart\x12\x19\n" +
	"\brent_end\x18\b \x01(\tR\arentEnd\x12\x1f\n" +
	"\vrent_amount\x18\t \x01(\x01R\n" +
	"rentAmount\x12\x18\n" +
	"\adeposit\x18\n" +
	" \x01(\x01R\adeposit\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1b\n" +
	"\tsigned_at\x18\f \x01(\tR\bsignedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12#\n" +
	"\rcancel_reason\x18\x10 \x01(\tR\fcancelReason\x12!\n" +
	"\fcancelled_at\x18\x11 \x01(\tR\vcancelledAt\"'\n" +
	"\x15GetOrderDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"D\n" +
	"\x13GetOrderDetailReply\x12-\n" +
	"\x05order\x18\x01 \x01(\v2\x17.api.order.v1.OrderInfoR\x05order\"F\n" +
	"\x13GetOrderListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"\x87\x01\n" +
	"\x11GetOrderListReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.api.order.v1.OrderInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x85\x02\n" +
	"\x12CreateOrderRequest\x12\x19\n" +
	"\bhouse_id\x18\x01 \x01(\rR\ahouseId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\rR\btenantId\x12\x1f\n" +
	"\vlandlord_id\x18\x03 \x01(\rR\n" +
	"landlordId\x12!\n" +
	"\ftenant_phone\x18\x04 \x01(\tR\vtenantPhone\x12\x1d\n" +
	"\n" +
	"rent_start\x18\x05 \x01(\tR\trentStart\x12\x19\n" +
	"\brent_end\x18\x06 \x01(\tR\arentEnd\x12\x1f\n" +
	"\vrent_amount\x18\a \x01(\x01R\n" +
	"rentAmount\x12\x18\n" +
	"\adeposit\x18\b \x01(\x01R\adeposit\"G\n" +
	"\x10CreateOrderReply\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x12CancelOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12#\n" +
	"\rcancel_reason\x18\x02 \x01(\tR\fcancelReason\"F\n" +
	"\x10CancelOrderReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xe0\x04\n" +
	"\x05Order\x12\x8f\x01\n" +
	"\x12GetTenantOrderList\x12'.api.order.v1.GetTenantOrderListRequest\x1a%.api.order.v1.GetTenantOrderListReply\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/orders/tenant/{tenant_id}\x12u\n" +
	"\x0eGetOrderDetail\x12#.api.order.v1.GetOrderDetailRequest\x1a!.api.order.v1.GetOrderDetailReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/orders/{id}\x12j\n" +
	"\fGetOrderList\x12!.api.order.v1.GetOrderListRequest\x1a\x1f.api.order.v1.GetOrderListReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/orders\x12j\n" +
	"\vCreateOrder\x12 .api.order.v1.CreateOrderRequest\x1a\x1e.api.order.v1.CreateOrderReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/orders\x12v\n" +
	"\vCancelOrder\x12 .api.order.v1.CancelOrderRequest\x1a\x1e.api.order.v1.CancelOrderReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/v1/orders/{id}/cancelB(\n" +
	"\fapi.order.v1P\x01Z\x16anjuke/api/order/v1;v1b\x06proto3"

var (
	file_api_order_v1_order_proto_rawDescOnce sync.Once
	file_api_order_v1_order_proto_rawDescData []byte
)

func file_api_order_v1_order_proto_rawDescGZIP() []byte {
	file_api_order_v1_order_proto_rawDescOnce.Do(func() {
		file_api_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)))
	})
	return file_api_order_v1_order_proto_rawDescData
}

var file_api_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_order_v1_order_proto_goTypes = []any{
	(*GetTenantOrderListRequest)(nil), // 0: api.order.v1.GetTenantOrderListRequest
	(*GetTenantOrderListReply)(nil),   // 1: api.order.v1.GetTenantOrderListReply
	(*OrderInfo)(nil),                 // 2: api.order.v1.OrderInfo
	(*GetOrderDetailRequest)(nil),     // 3: api.order.v1.GetOrderDetailRequest
	(*GetOrderDetailReply)(nil),       // 4: api.order.v1.GetOrderDetailReply
	(*GetOrderListRequest)(nil),       // 5: api.order.v1.GetOrderListRequest
	(*GetOrderListReply)(nil),         // 6: api.order.v1.GetOrderListReply
	(*CreateOrderRequest)(nil),        // 7: api.order.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),          // 8: api.order.v1.CreateOrderReply
	(*CancelOrderRequest)(nil),        // 9: api.order.v1.CancelOrderRequest
	(*CancelOrderReply)(nil),          // 10: api.order.v1.CancelOrderReply
}
var file_api_order_v1_order_proto_depIdxs = []int32{
	2,  // 0: api.order.v1.GetTenantOrderListReply.list:type_name -> api.order.v1.OrderInfo
	2,  // 1: api.order.v1.GetOrderDetailReply.order:type_name -> api.order.v1.OrderInfo
	2,  // 2: api.order.v1.GetOrderListReply.list:type_name -> api.order.v1.OrderInfo
	0,  // 3: api.order.v1.Order.GetTenantOrderList:input_type -> api.order.v1.GetTenantOrderListRequest
	3,  // 4: api.order.v1.Order.GetOrderDetail:input_type -> api.order.v1.GetOrderDetailRequest
	5,  // 5: api.order.v1.Order.GetOrderList:input_type -> api.order.v1.GetOrderListRequest
	7,  // 6: api.order.v1.Order.CreateOrder:input_type -> api.order.v1.CreateOrderRequest
	9,  // 7: api.order.v1.Order.CancelOrder:input_type -> api.order.v1.CancelOrderRequest
	1,  // 8: api.order.v1.Order.GetTenantOrderList:output_type -> api.order.v1.GetTenantOrderListReply
	4,  // 9: api.order.v1.Order.GetOrderDetail:output_type -> api.order.v1.GetOrderDetailReply
	6,  // 10: api.order.v1.Order.GetOrderList:output_type -> api.order.v1.GetOrderListReply
	8,  // 11: api.order.v1.Order.CreateOrder:output_type -> api.order.v1.CreateOrderReply
	10, // 12: api.order.v1.Order.CancelOrder:output_type -> api.order.v1.CancelOrderReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_order_v1_order_proto_init() }
func file_api_order_v1_order_proto_init() {
	if File_api_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_v1_order_proto_goTypes,
		DependencyIndexes: file_api_order_v1_order_proto_depIdxs,
		MessageInfos:      file_api_order_v1_order_proto_msgTypes,
	}.Build()
	File_api_order_v1_order_proto = out.File
	file_api_order_v1_order_proto_goTypes = nil
	file_api_order_v1_order_proto_depIdxs = nil
}
