// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user/v2/user.proto

package v2

import (
	v1 "anjuke/server/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建用户
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=Code,proto3" json:"Code,omitempty"` // 短信验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_v2_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateUserRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 创建用户响应数据
type CreateUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserData) Reset() {
	*x = CreateUserData{}
	mi := &file_user_v2_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserData) ProtoMessage() {}

func (x *CreateUserData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserData.ProtoReflect.Descriptor instead.
func (*CreateUserData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserData) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateUserData) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type RealNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IdCard        string                 `protobuf:"bytes,3,opt,name=IdCard,proto3" json:"IdCard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameRequest) Reset() {
	*x = RealNameRequest{}
	mi := &file_user_v2_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameRequest) ProtoMessage() {}

func (x *RealNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameRequest.ProtoReflect.Descriptor instead.
func (*RealNameRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{2}
}

func (x *RealNameRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RealNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RealNameRequest) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

// 实名认证响应数据
type RealNameData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // 认证状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameData) Reset() {
	*x = RealNameData{}
	mi := &file_user_v2_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameData) ProtoMessage() {}

func (x *RealNameData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameData.ProtoReflect.Descriptor instead.
func (*RealNameData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{3}
}

func (x *RealNameData) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RealNameData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RealNameData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// todo:修改实名
type UpdateUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusRequest) Reset() {
	*x = UpdateUserStatusRequest{}
	mi := &file_user_v2_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusRequest) ProtoMessage() {}

func (x *UpdateUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserStatusRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 更新用户状态响应数据
type UpdateUserStatusData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusData) Reset() {
	*x = UpdateUserStatusData{}
	mi := &file_user_v2_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusData) ProtoMessage() {}

func (x *UpdateUserStatusData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusData.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserStatusData) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatusData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Scene         string                 `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"` // 场景：register, login, reset_password, bind_phone 等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_user_v2_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{6}
}

func (x *SendSmsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendSmsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SendSmsRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

// 发送短信响应数据
type SendSmsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Scene         string                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 验证码过期时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsData) Reset() {
	*x = SendSmsData{}
	mi := &file_user_v2_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsData) ProtoMessage() {}

func (x *SendSmsData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsData.ProtoReflect.Descriptor instead.
func (*SendSmsData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{7}
}

func (x *SendSmsData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendSmsData) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *SendSmsData) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type VerifySmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`   // 用户输入的验证码
	Scene         string                 `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"` // 验证场景，需与发送时一致
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySmsRequest) Reset() {
	*x = VerifySmsRequest{}
	mi := &file_user_v2_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmsRequest) ProtoMessage() {}

func (x *VerifySmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmsRequest.ProtoReflect.Descriptor instead.
func (*VerifySmsRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{8}
}

func (x *VerifySmsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifySmsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifySmsRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

// 验证短信响应数据
type VerifySmsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 验证是否成功
	Scene         string                 `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySmsData) Reset() {
	*x = VerifySmsData{}
	mi := &file_user_v2_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySmsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmsData) ProtoMessage() {}

func (x *VerifySmsData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmsData.ProtoReflect.Descriptor instead.
func (*VerifySmsData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{9}
}

func (x *VerifySmsData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifySmsData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifySmsData) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

// 用户登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginType     string                 `protobuf:"bytes,1,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"` // 登录类型：password, sms
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`                        // 手机号
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                    // 密码（密码登录时使用）
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`                            // 验证码（短信登录时使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_v2_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{10}
}

func (x *LoginRequest) GetLoginType() string {
	if x != nil {
		return x.LoginType
	}
	return ""
}

func (x *LoginRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 用户登录响应数据
type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                              // JWT token
	ExpireTime    int64                  `protobuf:"varint,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // token过期时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_user_v2_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{11}
}

func (x *LoginData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginData) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginData) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *LoginData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginData) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// 获取文件列表请求
type GetFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`                    // 搜索关键词
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListRequest) Reset() {
	*x = GetFileListRequest{}
	mi := &file_user_v2_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListRequest) ProtoMessage() {}

func (x *GetFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListRequest.ProtoReflect.Descriptor instead.
func (*GetFileListRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFileListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetFileListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// 文件信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	UploadTime    string                 `protobuf:"bytes,6,opt,name=upload_time,json=uploadTime,proto3" json:"upload_time,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ObjectName    string                 `protobuf:"bytes,8,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_user_v2_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{13}
}

func (x *FileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileInfo) GetUploadTime() string {
	if x != nil {
		return x.UploadTime
	}
	return ""
}

func (x *FileInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileInfo) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

// 获取文件列表响应数据
type GetFileListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FileInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListData) Reset() {
	*x = GetFileListData{}
	mi := &file_user_v2_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListData) ProtoMessage() {}

func (x *GetFileListData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListData.ProtoReflect.Descriptor instead.
func (*GetFileListData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetFileListData) GetList() []*FileInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetFileListData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取上传统计请求
type GetUploadStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatsRequest) Reset() {
	*x = GetUploadStatsRequest{}
	mi := &file_user_v2_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatsRequest) ProtoMessage() {}

func (x *GetUploadStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUploadStatsRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{15}
}

// 获取上传统计响应数据
type GetUploadStatsData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalUploads   int32                  `protobuf:"varint,1,opt,name=total_uploads,json=totalUploads,proto3" json:"total_uploads,omitempty"`
	SuccessUploads int32                  `protobuf:"varint,2,opt,name=success_uploads,json=successUploads,proto3" json:"success_uploads,omitempty"`
	TotalSize      int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	TodayUploads   int32                  `protobuf:"varint,4,opt,name=today_uploads,json=todayUploads,proto3" json:"today_uploads,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUploadStatsData) Reset() {
	*x = GetUploadStatsData{}
	mi := &file_user_v2_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatsData) ProtoMessage() {}

func (x *GetUploadStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatsData.ProtoReflect.Descriptor instead.
func (*GetUploadStatsData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetUploadStatsData) GetTotalUploads() int32 {
	if x != nil {
		return x.TotalUploads
	}
	return 0
}

func (x *GetUploadStatsData) GetSuccessUploads() int32 {
	if x != nil {
		return x.SuccessUploads
	}
	return 0
}

func (x *GetUploadStatsData) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *GetUploadStatsData) GetTodayUploads() int32 {
	if x != nil {
		return x.TodayUploads
	}
	return 0
}

// 删除文件请求
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectName    string                 `protobuf:"bytes,1,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"` // 文件对象名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_user_v2_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteFileRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

// 删除文件响应数据
type DeleteFileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectName    string                 `protobuf:"bytes,1,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileData) Reset() {
	*x = DeleteFileData{}
	mi := &file_user_v2_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileData) ProtoMessage() {}

func (x *DeleteFileData) ProtoReflect() protoreflect.Message {
	mi := &file_user_v2_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileData.ProtoReflect.Descriptor instead.
func (*DeleteFileData) Descriptor() ([]byte, []int) {
	return file_user_v2_user_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteFileData) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *DeleteFileData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_v2_user_proto protoreflect.FileDescriptor

const file_user_v2_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v2/user.proto\x12\vapi.user.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x16common/v1/common.proto\"w\n" +
	"\x11CreateUserRequest\x12\x16\n" +
	"\x06Mobile\x18\x01 \x01(\tR\x06Mobile\x12\x1a\n" +
	"\bNickName\x18\x02 \x01(\tR\bNickName\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\x12\x12\n" +
	"\x04Code\x18\x04 \x01(\tR\x04Code\"^\n" +
	"\x0eCreateUserData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\"U\n" +
	"\x0fRealNameRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06IdCard\x18\x03 \x01(\tR\x06IdCard\"S\n" +
	"\fRealNameData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"1\n" +
	"\x17UpdateUserStatusRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"G\n" +
	"\x14UpdateUserStatusData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"Y\n" +
	"\x0eSendSmsRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05scene\x18\x03 \x01(\tR\x05scene\"Z\n" +
	"\vSendSmsData\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\"R\n" +
	"\x10VerifySmsRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05scene\x18\x03 \x01(\tR\x05scene\"U\n" +
	"\rVerifySmsData\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05scene\x18\x03 \x01(\tR\x05scene\"u\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\n" +
	"login_type\x18\x01 \x01(\tR\tloginType\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"\x90\x01\n" +
	"\tLoginData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x1f\n" +
	"\vexpire_time\x18\x05 \x01(\x03R\n" +
	"expireTime\"_\n" +
	"\x12GetFileListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"\xc2\x01\n" +
	"\bFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1f\n" +
	"\vupload_time\x18\x06 \x01(\tR\n" +
	"uploadTime\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vobject_name\x18\b \x01(\tR\n" +
	"objectName\"R\n" +
	"\x0fGetFileListData\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.api.user.v2.FileInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x17\n" +
	"\x15GetUploadStatsRequest\"\xa6\x01\n" +
	"\x12GetUploadStatsData\x12#\n" +
	"\rtotal_uploads\x18\x01 \x01(\x05R\ftotalUploads\x12'\n" +
	"\x0fsuccess_uploads\x18\x02 \x01(\x05R\x0esuccessUploads\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12#\n" +
	"\rtoday_uploads\x18\x04 \x01(\x05R\ftodayUploads\"4\n" +
	"\x11DeleteFileRequest\x12\x1f\n" +
	"\vobject_name\x18\x01 \x01(\tR\n" +
	"objectName\"K\n" +
	"\x0eDeleteFileData\x12\x1f\n" +
	"\vobject_name\x18\x01 \x01(\tR\n" +
	"objectName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xda\a\n" +
	"\x04User\x12b\n" +
	"\n" +
	"CreateUser\x12\x1e.api.user.v2.CreateUserRequest\x1a\x1b.api.common.v1.BaseResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/user/create\x12`\n" +
	"\bRealName\x12\x1c.api.user.v2.RealNameRequest\x1a\x1b.api.common.v1.BaseResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/user/realname\x12x\n" +
	"\x10UpdateUserStatus\x12$.api.user.v2.UpdateUserStatusRequest\x1a\x1b.api.common.v1.BaseResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/user/updateUserStatus\x12]\n" +
	"\aSendSms\x12\x1b.api.user.v2.SendSmsRequest\x1a\x1b.api.common.v1.BaseResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/user/sendSms\x12c\n" +
	"\tVerifySms\x12\x1d.api.user.v2.VerifySmsRequest\x1a\x1b.api.common.v1.BaseResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/user/verifySms\x12W\n" +
	"\x05Login\x12\x19.api.user.v2.LoginRequest\x1a\x1b.api.common.v1.BaseResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/login\x12:\n" +
	"\n" +
	"UploadFile\x12\x14.google.api.HttpBody\x1a\x14.google.api.HttpBody\"\x00\x12c\n" +
	"\vGetFileList\x12\x1f.api.user.v2.GetFileListRequest\x1a\x1b.api.common.v1.BaseResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/user/fileList\x12l\n" +
	"\x0eGetUploadStats\x12\".api.user.v2.GetUploadStatsRequest\x1a\x1b.api.common.v1.BaseResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/user/uploadStats\x12f\n" +
	"\n" +
	"DeleteFile\x12\x1e.api.user.v2.DeleteFileRequest\x1a\x1b.api.common.v1.BaseResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/file/{object_name}B:\n" +
	"\vapi.user.v2B\vUserProtoV2P\x01Z\x1canjuke/server/api/user/v2;v2b\x06proto3"

var (
	file_user_v2_user_proto_rawDescOnce sync.Once
	file_user_v2_user_proto_rawDescData []byte
)

func file_user_v2_user_proto_rawDescGZIP() []byte {
	file_user_v2_user_proto_rawDescOnce.Do(func() {
		file_user_v2_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v2_user_proto_rawDesc), len(file_user_v2_user_proto_rawDesc)))
	})
	return file_user_v2_user_proto_rawDescData
}

var file_user_v2_user_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_user_v2_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),       // 0: api.user.v2.CreateUserRequest
	(*CreateUserData)(nil),          // 1: api.user.v2.CreateUserData
	(*RealNameRequest)(nil),         // 2: api.user.v2.RealNameRequest
	(*RealNameData)(nil),            // 3: api.user.v2.RealNameData
	(*UpdateUserStatusRequest)(nil), // 4: api.user.v2.UpdateUserStatusRequest
	(*UpdateUserStatusData)(nil),    // 5: api.user.v2.UpdateUserStatusData
	(*SendSmsRequest)(nil),          // 6: api.user.v2.SendSmsRequest
	(*SendSmsData)(nil),             // 7: api.user.v2.SendSmsData
	(*VerifySmsRequest)(nil),        // 8: api.user.v2.VerifySmsRequest
	(*VerifySmsData)(nil),           // 9: api.user.v2.VerifySmsData
	(*LoginRequest)(nil),            // 10: api.user.v2.LoginRequest
	(*LoginData)(nil),               // 11: api.user.v2.LoginData
	(*GetFileListRequest)(nil),      // 12: api.user.v2.GetFileListRequest
	(*FileInfo)(nil),                // 13: api.user.v2.FileInfo
	(*GetFileListData)(nil),         // 14: api.user.v2.GetFileListData
	(*GetUploadStatsRequest)(nil),   // 15: api.user.v2.GetUploadStatsRequest
	(*GetUploadStatsData)(nil),      // 16: api.user.v2.GetUploadStatsData
	(*DeleteFileRequest)(nil),       // 17: api.user.v2.DeleteFileRequest
	(*DeleteFileData)(nil),          // 18: api.user.v2.DeleteFileData
	(*httpbody.HttpBody)(nil),       // 19: google.api.HttpBody
	(*v1.BaseResponse)(nil),         // 20: api.common.v1.BaseResponse
}
var file_user_v2_user_proto_depIdxs = []int32{
	13, // 0: api.user.v2.GetFileListData.list:type_name -> api.user.v2.FileInfo
	0,  // 1: api.user.v2.User.CreateUser:input_type -> api.user.v2.CreateUserRequest
	2,  // 2: api.user.v2.User.RealName:input_type -> api.user.v2.RealNameRequest
	4,  // 3: api.user.v2.User.UpdateUserStatus:input_type -> api.user.v2.UpdateUserStatusRequest
	6,  // 4: api.user.v2.User.SendSms:input_type -> api.user.v2.SendSmsRequest
	8,  // 5: api.user.v2.User.VerifySms:input_type -> api.user.v2.VerifySmsRequest
	10, // 6: api.user.v2.User.Login:input_type -> api.user.v2.LoginRequest
	19, // 7: api.user.v2.User.UploadFile:input_type -> google.api.HttpBody
	12, // 8: api.user.v2.User.GetFileList:input_type -> api.user.v2.GetFileListRequest
	15, // 9: api.user.v2.User.GetUploadStats:input_type -> api.user.v2.GetUploadStatsRequest
	17, // 10: api.user.v2.User.DeleteFile:input_type -> api.user.v2.DeleteFileRequest
	20, // 11: api.user.v2.User.CreateUser:output_type -> api.common.v1.BaseResponse
	20, // 12: api.user.v2.User.RealName:output_type -> api.common.v1.BaseResponse
	20, // 13: api.user.v2.User.UpdateUserStatus:output_type -> api.common.v1.BaseResponse
	20, // 14: api.user.v2.User.SendSms:output_type -> api.common.v1.BaseResponse
	20, // 15: api.user.v2.User.VerifySms:output_type -> api.common.v1.BaseResponse
	20, // 16: api.user.v2.User.Login:output_type -> api.common.v1.BaseResponse
	19, // 17: api.user.v2.User.UploadFile:output_type -> google.api.HttpBody
	20, // 18: api.user.v2.User.GetFileList:output_type -> api.common.v1.BaseResponse
	20, // 19: api.user.v2.User.GetUploadStats:output_type -> api.common.v1.BaseResponse
	20, // 20: api.user.v2.User.DeleteFile:output_type -> api.common.v1.BaseResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_v2_user_proto_init() }
func file_user_v2_user_proto_init() {
	if File_user_v2_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v2_user_proto_rawDesc), len(file_user_v2_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v2_user_proto_goTypes,
		DependencyIndexes: file_user_v2_user_proto_depIdxs,
		MessageInfos:      file_user_v2_user_proto_msgTypes,
	}.Build()
	File_user_v2_user_proto = out.File
	file_user_v2_user_proto_goTypes = nil
	file_user_v2_user_proto_depIdxs = nil
}
