// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.19.4
// source: upload/v1/upload.proto

package uploadv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUploadServiceSimpleUpload = "/api.upload.v1.UploadService/SimpleUpload"

type UploadServiceHTTPServer interface {
	// SimpleUpload 简单上传（小文件）
	SimpleUpload(context.Context, *SimpleUploadRequest) (*SimpleUploadReply, error)
}

func RegisterUploadServiceHTTPServer(s *http.Server, srv UploadServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/upload/smart", _UploadService_SimpleUpload0_HTTP_Handler(srv))
}

func _UploadService_SimpleUpload0_HTTP_Handler(srv UploadServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimpleUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUploadServiceSimpleUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SimpleUpload(ctx, req.(*SimpleUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SimpleUploadReply)
		return ctx.Result(200, reply)
	}
}

type UploadServiceHTTPClient interface {
	SimpleUpload(ctx context.Context, req *SimpleUploadRequest, opts ...http.CallOption) (rsp *SimpleUploadReply, err error)
}

type UploadServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUploadServiceHTTPClient(client *http.Client) UploadServiceHTTPClient {
	return &UploadServiceHTTPClientImpl{client}
}

func (c *UploadServiceHTTPClientImpl) SimpleUpload(ctx context.Context, in *SimpleUploadRequest, opts ...http.CallOption) (*SimpleUploadReply, error) {
	var out SimpleUploadReply
	pattern := "/api/upload/smart"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUploadServiceSimpleUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
