// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: transaction/v4/transaction.proto

package v4

import (
	v1 "anjuke/server/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_transaction_v4_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v4_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_v4_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 创建交易响应数据
type CreateTransactionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionData) Reset() {
	*x = CreateTransactionData{}
	mi := &file_transaction_v4_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionData) ProtoMessage() {}

func (x *CreateTransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v4_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionData.ProtoReflect.Descriptor instead.
func (*CreateTransactionData) Descriptor() ([]byte, []int) {
	return file_transaction_v4_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionData) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateTransactionData) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTransactionData) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTransactionData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTransactionData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_transaction_v4_transaction_proto protoreflect.FileDescriptor

const file_transaction_v4_transaction_proto_rawDesc = "" +
	"\n" +
	" transaction/v4/transaction.proto\x12\x12api.transaction.v4\x1a\x1cgoogle/api/annotations.proto\x1a\x16common/v1/common.proto\"\x81\x01\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xba\x01\n" +
	"\x15CreateTransactionData\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt2\x8d\x01\n" +
	"\vTransaction\x12~\n" +
	"\x11CreateTransaction\x12,.api.transaction.v4.CreateTransactionRequest\x1a\x1b.api.common.v1.BaseResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/transaction/createBO\n" +
	"\x12api.transaction.v4B\x12TransactionProtoV4P\x01Z#anjuke/server/api/transaction/v4;v4b\x06proto3"

var (
	file_transaction_v4_transaction_proto_rawDescOnce sync.Once
	file_transaction_v4_transaction_proto_rawDescData []byte
)

func file_transaction_v4_transaction_proto_rawDescGZIP() []byte {
	file_transaction_v4_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_v4_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_v4_transaction_proto_rawDesc), len(file_transaction_v4_transaction_proto_rawDesc)))
	})
	return file_transaction_v4_transaction_proto_rawDescData
}

var file_transaction_v4_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_v4_transaction_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil), // 0: api.transaction.v4.CreateTransactionRequest
	(*CreateTransactionData)(nil),    // 1: api.transaction.v4.CreateTransactionData
	(*v1.BaseResponse)(nil),          // 2: api.common.v1.BaseResponse
}
var file_transaction_v4_transaction_proto_depIdxs = []int32{
	0, // 0: api.transaction.v4.Transaction.CreateTransaction:input_type -> api.transaction.v4.CreateTransactionRequest
	2, // 1: api.transaction.v4.Transaction.CreateTransaction:output_type -> api.common.v1.BaseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_v4_transaction_proto_init() }
func file_transaction_v4_transaction_proto_init() {
	if File_transaction_v4_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_v4_transaction_proto_rawDesc), len(file_transaction_v4_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_v4_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_v4_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_v4_transaction_proto_msgTypes,
	}.Build()
	File_transaction_v4_transaction_proto = out.File
	file_transaction_v4_transaction_proto_goTypes = nil
	file_transaction_v4_transaction_proto_depIdxs = nil
}
