// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: api/payment/v1/payment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlipayPayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单号
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`                  // 金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayPayRequest) Reset() {
	*x = AlipayPayRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayPayRequest) ProtoMessage() {}

func (x *AlipayPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayPayRequest.ProtoReflect.Descriptor instead.
func (*AlipayPayRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *AlipayPayRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AlipayPayRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type AlipayPayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayUrl        string                 `protobuf:"bytes,1,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"` // 支付跳转链接（支付宝沙箱环境）
	QrCode        string                 `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"` // 二维码内容（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayPayReply) Reset() {
	*x = AlipayPayReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayPayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayPayReply) ProtoMessage() {}

func (x *AlipayPayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayPayReply.ProtoReflect.Descriptor instead.
func (*AlipayPayReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *AlipayPayReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *AlipayPayReply) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type AlipayQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayQueryRequest) Reset() {
	*x = AlipayQueryRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayQueryRequest) ProtoMessage() {}

func (x *AlipayQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayQueryRequest.ProtoReflect.Descriptor instead.
func (*AlipayQueryRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *AlipayQueryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type AlipayQueryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                  // 支付状态（如：SUCCESS、WAIT、FAIL）
	TradeNo       string                 `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"` // 支付宝交易号
	PayTime       string                 `protobuf:"bytes,4,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"` // 支付时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlipayQueryReply) Reset() {
	*x = AlipayQueryReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlipayQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlipayQueryReply) ProtoMessage() {}

func (x *AlipayQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlipayQueryReply.ProtoReflect.Descriptor instead.
func (*AlipayQueryReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *AlipayQueryReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AlipayQueryReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlipayQueryReply) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *AlipayQueryReply) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

var File_api_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payment/v1/payment.proto\x12\x0eapi.payment.v1\"E\n" +
	"\x10AlipayPayRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"B\n" +
	"\x0eAlipayPayReply\x12\x17\n" +
	"\apay_url\x18\x01 \x01(\tR\x06payUrl\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\"/\n" +
	"\x12AlipayQueryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"{\n" +
	"\x10AlipayQueryReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\btrade_no\x18\x03 \x01(\tR\atradeNo\x12\x19\n" +
	"\bpay_time\x18\x04 \x01(\tR\apayTime2\xad\x01\n" +
	"\aPayment\x12M\n" +
	"\tAlipayPay\x12 .api.payment.v1.AlipayPayRequest\x1a\x1e.api.payment.v1.AlipayPayReply\x12S\n" +
	"\vAlipayQuery\x12\".api.payment.v1.AlipayQueryRequest\x1a .api.payment.v1.AlipayQueryReplyB\x1aZ\x18anjuke/api/payment/v1;v1b\x06proto3"

var (
	file_api_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_payment_v1_payment_proto_rawDescData []byte
)

func file_api_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_payment_v1_payment_proto_rawDescData
}

var file_api_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_payment_v1_payment_proto_goTypes = []any{
	(*AlipayPayRequest)(nil),   // 0: api.payment.v1.AlipayPayRequest
	(*AlipayPayReply)(nil),     // 1: api.payment.v1.AlipayPayReply
	(*AlipayQueryRequest)(nil), // 2: api.payment.v1.AlipayQueryRequest
	(*AlipayQueryReply)(nil),   // 3: api.payment.v1.AlipayQueryReply
}
var file_api_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: api.payment.v1.Payment.AlipayPay:input_type -> api.payment.v1.AlipayPayRequest
	2, // 1: api.payment.v1.Payment.AlipayQuery:input_type -> api.payment.v1.AlipayQueryRequest
	1, // 2: api.payment.v1.Payment.AlipayPay:output_type -> api.payment.v1.AlipayPayReply
	3, // 3: api.payment.v1.Payment.AlipayQuery:output_type -> api.payment.v1.AlipayQueryReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_payment_v1_payment_proto_init() }
func file_api_payment_v1_payment_proto_init() {
	if File_api_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_api_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_payment_v1_payment_proto = out.File
	file_api_payment_v1_payment_proto_goTypes = nil
	file_api_payment_v1_payment_proto_depIdxs = nil
}
